version: "3.9"

services:

  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=meet-network"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/etc/proxy/traefik.yaml"
    ports:
      - "443:443"
    networks:
      - meet-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/traefik.yaml:/etc/proxy/traefik.yaml:ro"
      - "./proxy/cert.pem:/etc/proxy/certs/cert.pem:ro"
      - "./proxy/key.pem:/etc/proxy/certs/key.pem:ro"
  
  front:
    build: ./app
    ports:
      - "3000:3000"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  server-client:
    build:
      context: ./server-client
      dockerfile: docker/dev/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      
    networks:
      - meet-network
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-client.rule=Host(`localhost`) && PathPrefix(`/app`)"
      - "traefik.http.routers.server-client.entrypoints=websecure"
      - "traefik.http.routers.server-client.tls=true"
      - "traefik.http.services.server-client.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.app-strip.stripprefix.prefixes=/app"
      - "traefik.http.routers.server-client.middlewares=app-strip"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:8080/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  ws:
    build:
      context: ./ws
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:8081/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  test:
    profiles: ["test"]
    image: golang:1.25
    volumes:
      - .:/repo
    depends_on:
      - server-client
      - ws
    environment:
      FRONT_URL: http://front:3000
      API_URL: http://server-client:8080
      WS_URL: ws://ws:8081/ws

      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - meet-network
    command: >
      sh -c "
        cd /repo/server-client && go test ./... &&
        cd /repo/ws && go test ./... -p 1
      "

  seed:
    profiles: ["test"]
    image: postgres:15
    depends_on:
      - db
      - migrate
    volumes:
      - ./database/seed:/seed
    environment:
      PGPHOST: ${DB_HOST}
      PGPORT: 5432
      PGUSER: ${DB_USER}
      PGDATABASE: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
    networks:
      - meet-network
    entrypoint:
      - sh
      - -c
      - |
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/01_users_seed.sql &&
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/02_recruit_seed.sql &&
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/03_rooms_seed.sql &&
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/04_recruit_location_seed.sql &&
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/05_message_seed.sql &&
        psql -h db -U ${DB_USER} -d ${DB_NAME} -f /seed/06_authentication_seed.sql
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - meet-network
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.16.0
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
     - ./database/migrations:/migrations
    networks:
      - meet-network
    entrypoint:
      - migrate
      - -path
      - /migrations
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - up

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - meet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:

networks:
  meet-network:
    driver: bridge