package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	graph "server-client/internal/presenter/dto/gql/graph/generated"
	"server-client/internal/presenter/dto/gql/graph/model"
)

// MessagesByRoom is the resolver for the messagesByRoom field.
func (r *queryResolver) MessagesByRoom(ctx context.Context, roomID string) ([]*model.Message, error) {
	panic(fmt.Errorf("not implemented: MessagesByRoom - messagesByRoom"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
