package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	graph "server-client/internal/presenter/dto/gql/graph/generated"
	"server-client/internal/presenter/dto/gql/graph/model"
)

// CreateRecruit is the resolver for the createRecruit field.
func (r *mutationResolver) CreateRecruit(ctx context.Context, userID string, area string, imgURL string, man int32, woman int32, vacantMan int32, vacantWoman int32, comment string, date string, latitude float64, longitude float64) (*model.Recruit, error) {
	panic(fmt.Errorf("not implemented: CreateRecruit - createRecruit"))
}

// GetRecruits is the resolver for the getRecruits field.
func (r *queryResolver) GetRecruits(ctx context.Context, limit int32, offset int32) ([]*model.Recruit, error) {
	recruits, err := r.RecruitUsecase.GetRecruit(ctx, int(offset), int(limit))
	if err != nil {
		return nil, fmt.Errorf("failed to get recruits: %w", err)
	}

	var result []*model.Recruit
	for _, rec := range recruits {
		result = append(result, &model.Recruit{
			RecruitID:   rec.RecruitID().String(),
			UserID:      rec.UserID().String(),
			Area:        rec.Area(),
			ImgURL:      rec.ImgURL(),
			Man:         int32(rec.Man()),
			Woman:       int32(rec.Woman()),
			VacantMan:   int32(rec.VacantMan()),
			VacantWoman: int32(rec.VacantWoman()),
			Comment:     rec.Comment(),
			Date:        rec.Date().Format("2006-01-02"),
			Latitude:    rec.Latitude(),
			Longitude:   rec.Longitude(),
		})
	}
	return result, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
