package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"server-client/internal/presenter/dto/gql/graph/model"
)

// DeleteRoomUser is the resolver for the deleteRoomUser field.
func (r *mutationResolver) DeleteRoomUser(ctx context.Context, roomID string) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: DeleteRoomUser - deleteRoomUser"))
}

// GetRoomsByUser is the resolver for the getRoomsByUser field.
func (r *queryResolver) GetRoomsByUser(ctx context.Context, userID string, limit int32, offset int32) ([]*model.Room, error) {
	panic(fmt.Errorf("not implemented: GetRoomsByUser - getRoomsByUser"))
}
