// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"server-client/internal/application/usecase/query"
	query2 "server-client/internal/domain/repository/query"
	messagerepoimpl "server-client/internal/infrastructure/database/query/message_repo_impl"
	recruitrepoimpl "server-client/internal/infrastructure/database/query/recruit_repo_impl"
	roomrepoimpl "server-client/internal/infrastructure/database/query/room_repo_impl"
	userrepoimpl "server-client/internal/infrastructure/database/query/user_repo_impl"
	"server-client/internal/presenter/interface/gql/resolver"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB) *WireSet {
	messageRepoImpl := messagerepoimpl.NewMessageRepoImpl(db)
	messageUsecase := query.NewMessageUsecase(messageRepoImpl)
	roomRepoImpl := roomrepoimpl.NewRoomRepoImpl(db)
	roomUsecase := query.NewRoomUsecase(roomRepoImpl)
	userRepoImpl := userrepoimpl.NewUserRepoImpl(db)
	userUsecase := query.NewUserUsecase(userRepoImpl)
	recruitRepoImpl := recruitrepoimpl.NewRecruitRepoImpl(db)
	recruitUsecase := query.NewRecruitUsecase(recruitRepoImpl)
	resolverResolver := resolver.NewResolver(messageUsecase, roomUsecase, userUsecase, recruitUsecase)
	wireSet := &WireSet{
		Resolver:       resolverResolver,
		MessageUsecase: messageUsecase,
		RoomUsecase:    roomUsecase,
		UserUsecase:    userUsecase,
		RecruitUsecase: recruitUsecase,
		MessageRepo:    messageRepoImpl,
		RoomRepo:       roomRepoImpl,
		UserRepo:       userRepoImpl,
		RecruitRepo:    recruitRepoImpl,
	}
	return wireSet
}

// wire.go:

type WireSet struct {
	Resolver       *resolver.Resolver
	MessageUsecase *query.MessageUsecase
	RoomUsecase    *query.RoomUsecase
	UserUsecase    *query.UserUsecase
	RecruitUsecase *query.RecruitUsecase

	MessageRepo query2.MessageRepo
	RoomRepo    query2.RoomRepo
	UserRepo    query2.UserRepo
	RecruitRepo query2.RecruitRepo
}
