CREATE TABLE IF NOT EXISTS AUTHENTICATION (
    authid UUID PRIMARY KEY,
    userid UUID NOT NULL REFERENCES USERS(userid) ON DELETE CASCADE,
    sub VARCHAR(255) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    token VARCHAR(500),
    created_at TIMESTAMP
);
