CREATE TABLE IF NOT EXISTS RECRUIT_LOCATION (
    locationid UUID PRIMARY KEY,
    recruitid UUID NOT NULL REFERENCES RECRUIT(recruitid) ON DELETE CASCADE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);
