CREATE TABLE IF NOT EXISTS ROOMS (
    roomid UUID PRIMARY KEY,
    recruitid UUID NOT NULL REFERENCES RECRUIT(recruitid) ON DELETE CASCADE,
    userid UUID NOT NULL REFERENCES USERS(userid) ON DELETE CASCADE,
    role VARCHAR(50),
    isfinish BOOLEAN DEFAULT FALSE
);
