CREATE TABLE IF NOT EXISTS REVIEW (
    reviewid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    roomid UUID NOT NULL REFERENCES ROOMS(roomid) ON DELETE CASCADE,
    writer UUID NOT NULL REFERENCES USERS(userid) ON DELETE CASCADE,
    evaluated_user UUID NOT NULL REFERENCES USERS(userid) ON DELETE CASCADE,
    comment TEXT
);
