global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/proxy/traefik.yaml
    watch: true

tls:
  certificates:
    - certFile: /etc/proxy/certs/cert.pem
      keyFile: /etc/proxy/certs/key.pem