// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID       string `json:"id"`
	RoomID   string `json:"roomId"`
	SenderID string `json:"senderId"`
	Content  string `json:"content"`
	Isread   bool   `json:"isread"`
}

type Mutation struct {
}

type Query struct {
}

type Recruit struct {
	RecruitID   string  `json:"recruitId"`
	UserID      string  `json:"userId"`
	Area        string  `json:"area"`
	ImgURL      string  `json:"imgUrl"`
	Man         int32   `json:"man"`
	Woman       int32   `json:"woman"`
	VacantMan   int32   `json:"vacant_man"`
	VacantWoman int32   `json:"vacant_woman"`
	Comment     string  `json:"comment"`
	Date        string  `json:"date"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

type Room struct {
	RoomID     string `json:"roomId"`
	RecruitID  string `json:"recruitId"`
	UserID     string `json:"userId"`
	Role       string `json:"role"`
	Isfinished bool   `json:"isfinished"`
}

type User struct {
	UserID        string `json:"userId"`
	Username      string `json:"username"`
	Stars         int32  `json:"stars"`
	ImgURL        string `json:"imgUrl"`
	Pronunciation string `json:"pronunciation"`
	SelfIntroduce string `json:"selfIntroduce"`
}
